In [5]:
import pandas as pd 

df1 = pd.DataFrame({
    "id":[1,2,3],
    "customer_name":["Robert",'Peter','Dave'],
    "customer_id":[1,2,3]
}, columns = ["id","customer_id","customer_name"])

df1

   id  customer_id customer_name
0   1            1        Robert
1   2            2         Peter
2   3            3          Dave

In [7]:
import pandas as pd 

df2 = pd.DataFrame({
    "id":[1,2,4],
    "order_date":["2025-01-21",'2025-02-03','2025-09-01'],
    "order_id":[100,200,300]
}, columns = ["id","order_id","order_date"])

df2

   id  order_id  order_date
0   1       100  2025-01-21
1   2       200  2025-02-03
2   4       300  2025-09-01

In [ ]:
# 서로 다른 데이터 프레임을 하나로 합치는 방법 

# 1) concat() : 서로 다른 데이터 프레임을 단순 연결 (*교차되는 특정 인덱스를 고려x) -> 좌우 / 상하 합치기 가능 
# 2) merge() : 특정 인덱스를 기준

In [8]:
pd.concat([df1,df2])

   id  customer_id customer_name  order_id  order_date
0   1          1.0        Robert       NaN         NaN
1   2          2.0         Peter       NaN         NaN
2   3          3.0          Dave       NaN         NaN
0   1          NaN           NaN     100.0  2025-01-21
1   2          NaN           NaN     200.0  2025-02-03
2   4          NaN           NaN     300.0  2025-09-01

In [12]:
pd.merge(df1,df2)

# SQL 의 inner join 과 비슷함 
# 매칭되지 않는 id 값 : 3,4 는 탈락

   id  customer_id customer_name  order_id  order_date
0   1            1        Robert       100  2025-01-21
1   2            2         Peter       200  2025-02-03

In [13]:
pd.merge(df1,df2, on="id")

   id  customer_id customer_name  order_id  order_date
0   1            1        Robert       100  2025-01-21
1   2            2         Peter       200  2025-02-03

In [15]:
pd.merge(df1,df2,on="id", how = "outer")

   id  customer_id customer_name  order_id  order_date
0   1          1.0        Robert     100.0  2025-01-21
1   2          2.0         Peter     200.0  2025-02-03
2   3          3.0          Dave       NaN         NaN
3   4          NaN           NaN     300.0  2025-09-01

In [19]:
pd.merge(df1,df2,on="id", how = "right")

   id  customer_id customer_name  order_id  order_date
0   1          1.0        Robert       100  2025-01-21
1   2          2.0         Peter       200  2025-02-03
2   4          NaN           NaN       300  2025-09-01

In [20]:
pd.merge(df1,df2,on="id", how = "left")

   id  customer_id customer_name  order_id  order_date
0   1            1        Robert     100.0  2025-01-21
1   2            2         Peter     200.0  2025-02-03
2   3            3          Dave       NaN         NaN

In [21]:
df1 = df1.set_index("id")
df1

    customer_id customer_name
id
1             1        Robert
2             2         Peter
3             3          Dave

In [22]:
df2 = df2.set_index("id")
df2

    order_id  order_date
id
1        100  2025-01-21
2        200  2025-02-03
4        300  2025-09-01

In [24]:
pd.merge(df1,df2, left_index=True , right_index=True)

    customer_id customer_name  order_id  order_date
id
1             1        Robert       100  2025-01-21
2             2         Peter       200  2025-02-03

In [28]:
pd.merge(df1,df2,how="outer", left_index=True , right_index=True)

    customer_id customer_name  order_id  order_date
id
1           1.0        Robert     100.0  2025-01-21
2           2.0         Peter     200.0  2025-02-03
3           3.0          Dave       NaN         NaN
4           NaN           NaN     300.0  2025-09-01

In [29]:
pd.merge(df1,df2,how="left", left_index=True , right_index=True)

    customer_id customer_name  order_id  order_date
id
1             1        Robert     100.0  2025-01-21
2             2         Peter     200.0  2025-02-03
3             3          Dave       NaN         NaN

In [30]:
pd.merge(df1,df2,how="right", left_index=True , right_index=True)

    customer_id customer_name  order_id  order_date
id
1           1.0        Robert       100  2025-01-21
2           2.0         Peter       200  2025-02-03
4           NaN           NaN       300  2025-09-01

In [33]:
df = pd.DataFrame({
    "영어" : [60,70], 
    "수학" : [100,50], 
    
},columns = ["영어","수학"],index=["Dave","David"])

df

       영어   수학
Dave   60  100
David  70   50

In [38]:
# def func(df_data) : 
#     print(type(df_data))
#     print(df_data.index)
#     print(df_data.values)
#     return df_data
def func(df_data) :
    df_data["영어"] = 80
    return df_data

In [40]:
df_func = df.apply(func,axis = 1)
df

       영어   수학
Dave   80  100
David  80   50

In [41]:
df = pd.DataFrame({
    "성별" : ["남","남","남"], 
    "이름" : ["David","Dave","Dave"],
    "수학" : [100,50,80],
    "국어" : [80,70,50]
})

df

  성별     이름   수학  국어
0  남  David  100  80
1  남   Dave   50  70
2  남   Dave   80  50

In [44]:
selected_columns = ["이름","수학","국어"]

df = df[selected_columns] 
# df.groupby("이름").sum()
df.groupby("이름").mean()

          수학    국어
이름
Dave    65.0  60.0
David  100.0  80.0

In [48]:
import os 

PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/" 

file_list, csv_list = os.listdir(PATH) , list()

for

FileNotFoundError: [WinError 3] 지정된 경로를 찾을 수 없습니다: 'COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/'