In [1]:
import pandas as pd

PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"
doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig")

In [2]:
doc.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"

In [7]:
# 데이터 프레임 내 특정 컬럼만 찾아오는 방법

countries = doc["Country_Region"]
countries
# countries.head()

0                   US
1                   US
2                   US
3                   US
4                   US
             ...
2517    United Kingdom
2518             Nauru
2519       New Zealand
2520            Tuvalu
2521    United Kingdom
Name: Country_Region, Length: 2522, dtype: object

In [8]:
# 찾아온 데이터의 전체 크기, 결측치가 아닌 정상값을 가지고 있는 데이터의 크기

print(countries.size, countries.count())

2522 2522

In [18]:
# 중복되어있는 데이터들을 대표하는 대표값만 출력

print(countries.unique())

['US' 'Canada' 'United Kingdom' 'China' 'Netherlands' 'Australia'
 'Denmark' 'France' 'Afghanistan' 'Albania' 'Algeria' 'Andorra' 'Angola'
 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Austria' 'Azerbaijan'
 'Bahamas' 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize'
 'Benin' 'Bhutan' 'Bolivia' 'Bosnia and Herzegovina' 'Botswana' 'Brazil'
 'Brunei' 'Bulgaria' 'Burkina Faso' 'Burma' 'Burundi' 'Cabo Verde'
 'Cambodia' 'Cameroon' 'Central African Republic' 'Chad' 'Chile'
 'Colombia' 'Congo (Brazzaville)' 'Congo (Kinshasa)' 'Costa Rica'
 "Cote d'Ivoire" 'Croatia' 'Cuba' 'Cyprus' 'Czechia' 'Diamond Princess'
 'Djibouti' 'Dominica' 'Dominican Republic' 'Ecuador' 'Egypt'
 'El Salvador' 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini'
 'Ethiopia' 'Fiji' 'Finland' 'Gabon' 'Gambia' 'Georgia' 'Germany' 'Ghana'
 'Greece' 'Grenada' 'Guatemala' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti'
 'Holy See' 'Honduras' 'Hungary' 'Iceland' 'India' 'Indonesia' 'Iran'
 'Iraq' 'Ireland' 'Israel' 'Italy' 'Jamaica' 'Japan' 'Jordan' 'Kazakhstan'
 'Kenya' 'Korea, South' 'Kosovo' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Latvia'
 'Lebanon' 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania' 'Luxembourg'
 'MS Zaandam' 'Madagascar' 'Maldives' 'Mali' 'Malta' 'Mauritania'
 'Mauritius' 'Mexico' 'Moldova' 'Monaco' 'Mongolia' 'Montenegro' 'Morocco'
 'Mozambique' 'Namibia' 'Nepal' 'New Zealand' 'Nicaragua' 'Niger'
 'Nigeria' 'North Macedonia' 'Norway' 'Oman' 'Pakistan' 'Panama'
 'Papua New Guinea' 'Paraguay' 'Peru' 'Philippines' 'Poland' 'Portugal'
 'Qatar' 'Romania' 'Russia' 'Rwanda' 'Saint Kitts and Nevis' 'Saint Lucia'
 'Saint Vincent and the Grenadines' 'Samoa' 'San Marino' 'Saudi Arabia'
 'Senegal' 'Serbia' 'Seychelles' 'Sierra Leone' 'Singapore' 'Slovakia'
 'Slovenia' 'Somalia' 'South Africa' 'Spain' 'Sri Lanka' 'Sudan'
 'Suriname' 'Sweden' 'Switzerland' 'Syria' 'Taiwan*' 'Tanzania' 'Thailand'
 'Timor-Leste' 'Togo' 'Trinidad and Tobago' 'Tunisia' 'Turkey' 'Uganda'
 'Ukraine' 'United Arab Emirates' 'Uruguay' 'Uzbekistan' 'Venezuela'
 'Vietnam' 'West Bank and Gaza' 'Zambia' 'Zimbabwe' 'Kiribati' 'Palau'
 'Summer Olympics 2020' 'Malaysia' 'Tonga' 'Winter Olympics 2022'
 'Antarctica' 'Korea, North' 'Nauru' 'Tuvalu']

In [17]:
# 대표값들의 카운트 횟수

countries.value_counts()

Country_Region
US                2228
China               34
United Kingdom      18
Malaysia            17
Canada              16
                  ...
Ghana                1
Greece               1
Grenada              1
Guatemala            1
Tuvalu               1
Name: count, Length: 190, dtype: int64

In [12]:
covid_stat = doc[["Confirmed", "Deaths", "Recovered"]]
covid_stat.head()

   Confirmed  Deaths  Recovered
0          4       0          0
1         47       1          0
2          7       0          0
3        195       3          0
4          1       0          0

In [16]:
# 컬럼 내 특정조건에 부합하는 데이터만 찾아오는 방법

doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig")
doc

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"
...,...,...,...,...,...,...,...,...,...,...,...,...
2517,82604.0,NaN,Wales,United Kingdom,2020-04-01 21:58:49,52.130700,-3.783700,0,198,0,0,"Wales, United Kingdom"
2518,NaN,NaN,NaN,Nauru,2020-04-01 21:58:49,-0.522800,166.931500,0,0,0,0,Nauru
2519,NaN,NaN,Niue,New Zealand,2020-04-01 21:58:49,-19.054400,-169.867200,0,0,0,0,"Niue, New Zealand"
2520,NaN,NaN,NaN,Tuvalu,2020-04-01 21:58:49,-7.109500,177.649300,0,0,0,0,Tuvalu
2521,NaN,NaN,Pitcairn Islands,United Kingdom,2020-04-01 21:58:49,-24.376800,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom"

In [15]:
doc_us = doc[doc["Country_Region"] == "US"]
doc_us

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"
...,...,...,...,...,...,...,...,...,...,...,...,...
2246,66000.0,NaN,Guam,US,2020-04-01 21:58:49,13.444300,144.793700,77,3,0,74,"Guam, US"
2273,NaN,NaN,Northern Mariana Islands,US,2020-04-01 21:58:49,15.097900,145.673900,2,0,0,2,",Northern Mariana Islands,US"
2280,NaN,NaN,Puerto Rico,US,2020-04-01 21:58:49,18.220800,-66.590100,286,11,0,275,"Puerto Rico, US"
2285,NaN,NaN,Recovered,US,2020-04-01 21:58:49,0.000000,0.000000,0,0,8474,0,"Recovered, US"
2303,NaN,NaN,Virgin Islands,US,2020-04-01 21:58:49,18.335800,-64.896300,30,0,0,30,",Virgin Islands,US"

In [21]:
# NaN = Not a Number = null

doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig")
doc.isnull().sum()

FIPS              347
Admin2            301
Province_State    184
Country_Region      0
Last_Update         0
Lat                 4
Long_               4
Confirmed           0
Deaths              0
Recovered           0
Active              0
Combined_Key        0
dtype: int64

In [23]:
doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig")
doc = doc.dropna()
doc.isnull().sum()

FIPS              0
Admin2            0
Province_State    0
Country_Region    0
Last_Update       0
Lat               0
Long_             0
Confirmed         0
Deaths            0
Recovered         0
Active            0
Combined_Key      0
dtype: int64

In [25]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")
doc = doc.dropna()
doc.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
13,Hubei,Mainland China,1/22/2020 17:00,444.0,17.0,28.0
41,Cook Islands,New Zealand,1/22/2020 17:00,0.0,0.0,0.0
43,Johor,Malaysia,1/22/2020 17:00,0.0,0.0,0.0
44,Kedah,Malaysia,1/22/2020 17:00,0.0,0.0,0.0
45,Kelantan,Malaysia,1/22/2020 17:00,0.0,0.0,0.0

In [29]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")
doc = doc.dropna(subset=["Confirmed"])
doc.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
1,Beijing,Mainland China,1/22/2020 17:00,14.0,NaN,NaN
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,NaN,NaN
3,Fujian,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
5,Guangdong,Mainland China,1/22/2020 17:00,26.0,NaN,NaN

In [30]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")
doc = doc.fillna(0)
doc.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0

In [32]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")
nan_data = {"Deaths": 0, "Recovered": 0}
doc = doc.fillna(nan_data)
doc.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,Gansu,Mainland China,1/22/2020 17:00,NaN,0.0,0.0

In [33]:
doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig")
doc.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"

In [34]:
doc = doc.groupby("Country_Region").sum()
doc.head()

,FIPS,Admin2,Province_State,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
Country_Region,,,,,,,,,,,
Afghanistan,0.0,0,0,2020-04-01 21:58:34,33.93911,67.709953,192,4,5,183,Afghanistan
Albania,0.0,0,0,2020-04-01 21:58:34,41.15330,20.168300,259,15,67,177,Albania
Algeria,0.0,0,0,2020-04-01 21:58:34,28.03390,1.659600,847,58,61,728,Algeria
Andorra,0.0,0,0,2020-04-01 21:58:34,42.50630,1.521800,390,14,10,366,Andorra
Angola,0.0,0,0,2020-04-01 21:58:34,-11.20270,17.873900,8,2,1,5,Angola

In [35]:
doc.columns

Index(['FIPS', 'Admin2', 'Province_State', 'Last_Update', 'Lat', 'Long_',
       'Confirmed', 'Deaths', 'Recovered', 'Active', 'Combined_Key'],
      dtype='object')

In [36]:
doc.index

Index(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antarctica',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       ...
       'United Arab Emirates', 'United Kingdom', 'Uruguay', 'Uzbekistan',
       'Venezuela', 'Vietnam', 'West Bank and Gaza', 'Winter Olympics 2022',
       'Zambia', 'Zimbabwe'],
      dtype='object', name='Country_Region', length=190)

In [37]:
doc[doc.index == "US"]

,FIPS,Admin2,Province_State,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
Country_Region,,,,,,,,,,,
US,65168934.0,AbbevilleAcadiaAccomackAdaAdairAdairAdairAdams...,South CarolinaLouisianaVirginiaIdahoIowaMissou...,2020-04-01 21:58:492020-04-01 21:58:492020-04-...,82956.96013,-197553.963757,216936,5222,8474,209150,"Abbeville, South Carolina, USAcadia, Louisiana..."

In [38]:
# 컬럼 타입 변경

import pandas as pd
PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"

In [41]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")
doc = doc[["Country/Region", "Confirmed"]]
doc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country/Region  76 non-null     object
 1   Confirmed       66 non-null     float64
dtypes: float64(1), object(1)
memory usage: 1.3+ KB

In [43]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")
doc = doc[["Country/Region", "Confirmed"]]
doc = doc.dropna(subset=["Confirmed"])
doc = doc.astype({"Confirmed": "int64"})
doc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 66 entries, 0 to 75
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country/Region  66 non-null     object
 1   Confirmed       66 non-null     int64
dtypes: int64(1), object(1)
memory usage: 1.5+ KB

In [47]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")
doc = doc[["Country/Region", "Confirmed"]]
doc = doc.dropna(subset=["Confirmed"])
doc = doc.astype({"Confirmed": "int64"}) # 특정 컬럼의 타입을 변경하기 전, 반드시 결측치 값이 존재 x
doc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 66 entries, 0 to 75
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country/Region  66 non-null     object
 1   Confirmed       66 non-null     int64
dtypes: int64(1), object(1)
memory usage: 1.5+ KB

In [48]:
doc.head()

   Country/Region  Confirmed
0  Mainland China          1
1  Mainland China         14
2  Mainland China          6
3  Mainland China          1
5  Mainland China         26